import type{Env}from'./types';
type Ctx={env:Env,user?:any};const json=(data:any,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json;charset=utf-8'}});const err=(m:string,s=400)=>json({error:m},s);
const b64=(b:ArrayBuffer)=>btoa(String.fromCharCode(...new Uint8Array(b))).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_');
async function hashPassword(password:string,salt?:string){salt=salt||crypto.randomUUID();const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(salt),iterations:120000,hash:'SHA-256'},key,256);return `${salt}.${b64(bits)}`}
async function verifyPassword(password:string,stored:string){const[salt]=stored.split('.');return await hashPassword(password,salt)===stored}
async function sign(payload:any,secret:string){const header=b64(new TextEncoder().encode(JSON.stringify({alg:'HS256',typ:'JWT'})).buffer);const body=b64(new TextEncoder().encode(JSON.stringify({...payload,exp:Date.now()+7*864e5})).buffer);const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=b64(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(`${header}.${body}`)));return `${header}.${body}.${sig}`}
async function auth(req:Request,env:Env){const t=req.headers.get('authorization')?.replace('Bearer ','');if(!t)return null;const[h,b,s]=t.split('.');const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(env.JWT_SECRET),{name:'HMAC',hash:'SHA-256'},false,['verify']);if(!await crypto.subtle.verify('HMAC',key,Uint8Array.from(atob(s.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0)),new TextEncoder().encode(`${h}.${b}`)))return null;const p=JSON.parse(atob(b.replace(/-/g,'+').replace(/_/g,'/')));return p.exp>Date.now()?p:null}
const asaasBase=(e:Env)=>e.ASAAS_ENV==='production'?'https://api.asaas.com/v3':'https://api-sandbox.asaas.com/v3';async function asaas(env:Env,path:string,method='GET',body?:any){const r=await fetch(asaasBase(env)+path,{method,headers:{'content-type':'application/json','access_token':env.ASAAS_API_KEY,'User-Agent':'AFIT-Cloudflare/1.0'},body:body?JSON.stringify(body):undefined});const d:any=await r.json();if(!r.ok)throw new Error(d.errors?.[0]?.description||'Erro ao comunicar com o Asaas');return d}
async function route(req:Request,env:Env){const u=new URL(req.url),p=u.pathname,m=req.method;let user=await auth(req,env);
 if(p==='/api/setup/admin'&&m==='POST'){if(req.headers.get('x-setup-token')!==env.SETUP_TOKEN)return err('Token de configuração inválido',403);const b:any=await req.json();const exists=await env.DB.prepare('SELECT id FROM users WHERE role=?').bind('admin').first();if(exists)return err('Administrador já configurado');await env.DB.prepare('INSERT INTO users(name,email,password_hash,role,subscription_status) VALUES(?,?,?,?,?)').bind(b.name,b.email.toLowerCase(),await hashPassword(b.password),'admin','ACTIVE').run();return json({ok:true})}
 if(p==='/api/auth/register'&&m==='POST'){const b:any=await req.json();if(!b.email||!b.password||b.password.length<8)return err('Informe e-mail e senha com pelo menos 8 caracteres.');try{const r=await env.DB.prepare('INSERT INTO users(name,email,password_hash,role,cpf,phone,subscription_status) VALUES(?,?,?,?,?,?,?) RETURNING id').bind(b.name,b.email.toLowerCase(),await hashPassword(b.password),'student',b.cpf,b.phone,'INACTIVE').first<any>();const usr={id:r.id,name:b.name,email:b.email.toLowerCase(),role:'student',subscriptionStatus:'INACTIVE'};return json({token:await sign(usr,env.JWT_SECRET),user:usr})}catch{return err('E-mail já cadastrado.')}}
 if(p==='/api/auth/login'&&m==='POST'){const b:any=await req.json();const x:any=await env.DB.prepare('SELECT * FROM users WHERE email=?').bind(String(b.email).toLowerCase()).first();if(!x||!await verifyPassword(b.password,x.password_hash))return err('E-mail ou senha inválidos.',401);const usr={id:x.id,name:x.name,email:x.email,role:x.role,subscriptionStatus:x.subscription_status};return json({token:await sign(usr,env.JWT_SECRET),user:usr})}
 if(p==='/api/auth/me'){if(!user)return err('Não autenticado',401);const x:any=await env.DB.prepare('SELECT id,name,email,role,subscription_status FROM users WHERE id=?').bind(user.id).first();return json({user:{id:x.id,name:x.name,email:x.email,role:x.role,subscriptionStatus:x.subscription_status}})}
 if(p==='/api/plans'){const rows=await env.DB.prepare('SELECT id,name,price,period,description FROM plans WHERE active=1').all();return json({plans:rows.results})}
 if(p==='/api/asaas/webhook'&&m==='POST'){if(req.headers.get('asaas-access-token')!==env.ASAAS_WEBHOOK_TOKEN)return err('Webhook não autorizado',401);const b:any=await req.json();const payment=b.payment;if(payment?.id){await env.DB.prepare('UPDATE payments SET status=?,updated_at=CURRENT_TIMESTAMP WHERE asaas_payment_id=?').bind(payment.status,payment.id).run();if(['RECEIVED','CONFIRMED','RECEIVED_IN_CASH'].includes(payment.status)){const row:any=await env.DB.prepare('SELECT user_id,plan_id FROM payments WHERE asaas_payment_id=?').bind(payment.id).first();if(row){const plan:any=await env.DB.prepare('SELECT duration_days FROM plans WHERE id=?').bind(row.plan_id).first();const until=new Date(Date.now()+(plan?.duration_days||30)*864e5).toISOString();await env.DB.prepare("UPDATE users SET subscription_status='ACTIVE',subscription_until=? WHERE id=?").bind(until,row.user_id).run()}}}return new Response(null,{status:204})}
 if(p.startsWith('/media/')){const key=decodeURIComponent(p.slice(7));const o=await env.MEDIA.get(key);if(!o)return new Response('Arquivo não encontrado',{status:404});return new Response(o.body,{headers:{'content-type':o.httpMetadata?.contentType||'application/octet-stream','cache-control':'public,max-age=86400'}})}
 if(!user)return err('Não autenticado',401);
 if(p==='/api/payments/checkout'&&m==='POST'){if(user.role!=='student')return err('Operação exclusiva para alunos',403);const b:any=await req.json();const plan:any=await env.DB.prepare('SELECT * FROM plans WHERE id=? AND active=1').bind(b.planId).first();const usr:any=await env.DB.prepare('SELECT * FROM users WHERE id=?').bind(user.id).first();if(!plan)return err('Plano inválido');let customer=usr.asaas_customer_id;if(!customer){const c=await asaas(env,'/customers','POST',{name:usr.name,cpfCnpj:usr.cpf,email:usr.email,mobilePhone:usr.phone,externalReference:String(usr.id)});customer=c.id;await env.DB.prepare('UPDATE users SET asaas_customer_id=? WHERE id=?').bind(customer,user.id).run()}const due=new Date(Date.now()+3*864e5).toISOString().slice(0,10);const pay=await asaas(env,'/payments','POST',{customer,billingType:'UNDEFINED',value:plan.price,dueDate:due,description:`AFIT - ${plan.name}`,externalReference:`user:${user.id}|plan:${plan.id}`});await env.DB.prepare('INSERT INTO payments(user_id,plan_id,asaas_payment_id,status,value,invoice_url) VALUES(?,?,?,?,?,?)').bind(user.id,plan.id,pay.id,pay.status,plan.price,pay.invoiceUrl||pay.bankSlipUrl).run();return json({invoiceUrl:pay.invoiceUrl||pay.bankSlipUrl,paymentId:pay.id})}
 if(p==='/api/payments/status'){const x:any=await env.DB.prepare('SELECT subscription_status FROM users WHERE id=?').bind(user.id).first();return json({status:x.subscription_status})}
 if(p==='/api/student/content'){const x:any=await env.DB.prepare('SELECT subscription_status FROM users WHERE id=?').bind(user.id).first();if(x.subscription_status!=='ACTIVE')return err('Plano sem pagamento confirmado',402);const [e,t,d]=await Promise.all([env.DB.prepare('SELECT id,name,training_category AS trainingCategory,muscle_group AS muscleGroup,level,execution_mode AS executionMode,description,objective,instructions,benefits,common_errors AS commonErrors,equipment,sets,reps,duration,rest,tags,video_url AS videoUrl,image_url AS imageUrl FROM exercises WHERE active=1 ORDER BY training_category,name').all(),env.DB.prepare('SELECT * FROM tips WHERE active=1 ORDER BY id DESC').all(),env.DB.prepare('SELECT id,time,title,description FROM diet_items WHERE user_id=? ORDER BY sort_order,id').bind(user.id).all()]);return json({exercises:e.results,tips:t.results,diet:d.results})}
 if(p.startsWith('/api/admin/')){if(user.role!=='admin')return err('Acesso restrito',403);const kind=p.split('/')[3];if(kind==='upload'&&m==='POST'){const fd=await req.formData();const f=fd.get('file');if(!(f instanceof File))return err('Arquivo inválido');if(f.size>200*1024*1024)return err('O arquivo excede o limite de 200 MB.');const key=`uploads/${Date.now()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;await env.MEDIA.put(key,f.stream(),{httpMetadata:{contentType:f.type}});return json({key,url:`/media/${encodeURIComponent(key)}`})}const defs:any={exercises:{table:'exercises',select:'SELECT id,name,training_category AS trainingCategory,muscle_group AS muscleGroup,level,execution_mode AS executionMode,description,objective,instructions,benefits,common_errors AS commonErrors,equipment,sets,reps,duration,rest,tags,video_url AS videoUrl,image_url AS imageUrl,active FROM exercises ORDER BY id DESC',sql:'INSERT INTO exercises(name,training_category,muscle_group,level,execution_mode,description,objective,instructions,benefits,common_errors,equipment,sets,reps,duration,rest,tags,video_url,image_url) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',vals:(b:any)=>[b.name,b.trainingCategory||'Musculação',b.muscleGroup,b.level||'Iniciante',b.executionMode||'Repetições',b.description,b.objective,b.instructions,b.benefits,b.commonErrors,b.equipment,Number(b.sets||0),b.reps,b.duration,b.rest,b.tags,b.videoUrl,b.imageUrl]},tips:{table:'tips',select:'SELECT * FROM tips ORDER BY id DESC',sql:'INSERT INTO tips(title,description,category,video_url,image_url) VALUES(?,?,?,?,?)',vals:(b:any)=>[b.title,b.description,b.category,b.videoUrl,b.imageUrl]},diets:{table:'diet_items',select:'SELECT d.*,u.email FROM diet_items d JOIN users u ON u.id=d.user_id ORDER BY d.id DESC',sql:'INSERT INTO diet_items(user_id,time,title,description) SELECT id,?,?,? FROM users WHERE email=?',vals:(b:any)=>[b.time,b.title,b.description,b.studentEmail]},students:{select:"SELECT id,name,email,subscription_status,subscription_until FROM users WHERE role='student' ORDER BY id DESC"}};const d=defs[kind];if(!d)return err('Recurso inválido',404);if(m==='GET'){const r=await env.DB.prepare(d.select).all();return json({items:r.results})}if(m==='POST'&&d.sql){const b:any=await req.json();await env.DB.prepare(d.sql).bind(...d.vals(b)).run();return json({ok:true})}}
 return null}
export default{async fetch(req:Request,env:Env){try{const r=await route(req,env);return r||env.ASSETS.fetch(req)}catch(e:any){console.error(e);return err(e.message||'Erro interno',500)}}};
